### PR TITLE
Tailwind css pagination fix

### LINKED ISSUE #22: Broken pagination on tailwind branch
The pagination on Tailwind branch is currently broken.

### PR DESCRIPTION
**Pull request by SUdoWinchester**
- Criado a tela de show user;
- Retirado a função de deletar registros do datalist e criado um componente especifico pra isso;
- Criado componente para o footer da paginação;

Fixes #22

### CODE REVIEW

File: project/resources/js/Components/Confirmable.vue [hunk 1]
```diff
@@ -8,7 +8,7 @@ To use:
     </confirmable>
 -->
 <template>
-  <div>
+  <div class="inline">
```
Comment (danilopinotti) [inline project/resources/js/Components/Confirmable.vue:11]: This will broke.
Its recommended keep without classes.

You may set the class on this utilization:
`<confirmable class="inline" ...> </coonfirmable>`

File: project/resources/js/Components/Pagination.vue [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+    shouldShowPagination() {
+      return this.$parent.shouldShowPagination;
+    },
+
+    enabledPrevPageButton() {
+      return this.$parent.enabledPrevPageButton;
+    },
+
+    enabledNextPageButton() {
+      return this.$parent.enabledNextPageButton;
```
Comment (danilopinotti) [inline project/resources/js/Components/Pagination.vue:53]: You shouldn't access $parent (or $root, or any other component) using this approach.

Communication between `parent -> child` is using `props`.
Communication between `child -> parent` is using `events`.

[Read more about communication between components accessing this link](https://medium.com/js-dojo/component-communication-in-vue-js-ca8b591d7efa)

File: project/app/Http/Controllers/UserController.php [hunk 3]
```diff
@@ -60,6 +60,7 @@ public function pagination()
     {
         return pagination()
             ->repository(UserRepository::class)
-            ->resource(UserResource::class);
+            ->resource(UserResource::class)
+            ->perPage(10);
```
Comment (danilopinotti) [inline project/app/Http/Controllers/UserController.php:64]: Keep the `perPage` implicit.

File: project/resources/js/Components/DataList.vue [hunk 4]
```diff
@@ -8,19 +8,27 @@
...
             <tbody>
-                <slot name="body" :items="items"></slot>
+                <slot name="body" :fetchData="fetchData" :items="items"></slot>
             </tbody>
         </table>
 
-        <slot name="footer"></slot>
+        <pagination
+          class="w-10/12"
+          :pagination-buttons="paginationButtons"
```
Comment (danilopinotti) [inline project/resources/js/Components/DataList.vue:17]: The button generation is a responsibility of Pagination component.

File: project/resources/js/Components/DataList.vue [hunk 5]
```diff
@@ -8,19 +8,31 @@
...
+                <slot name="body" :fetchData="fetchData" :items="items"></slot>
             </tbody>
         </table>
 
-        <slot name="footer"></slot>
+        <pagination
+          class="w-10/12"
+          :total-pages="totalPages"
+          :current-page="currentPage"
+          :shouldShowPagination="shouldShowPagination"
```
Comment (danilopinotti) [inline project/resources/js/Components/DataList.vue:19]: shouldShowPagination, enabledPrevPageButton and enabledNextPageButton can be computed inside pagination component

File: project/resources/js/Components/DataList.vue [hunk 6]
```diff
@@ -8,19 +8,31 @@
...
+          :enabledPrevPageButton="enabledPrevPageButton"
+          :enabledNextPageButton="enabledNextPageButton"
+          @fetchPrevPage="fetchPrevPage"
```
Comment (danilopinotti) [inline project/resources/js/Components/DataList.vue:22]: I think `fetchPrevPage` and `fetchNextPage` can be substituted to only `changePage`, and then, removed from DataList.
